### ISSUE TITLE
[BUG] Conformance Owner is not accepting all devmod modules from client

### ISSUE THREAD

**Issue by Sai-Anudeep47** [fido-alliance/fdo-fido-conformance-server#52] opened 2023-09-27 16:37 UTC
To simplify issue resolution process, please provide network logs, and or test voucher.
[client_msg68_devmod_err.log](https://github.com/fido-alliance/fdo-fido-conformance-server/files/12741029/client_msg68_devmod_err.log)
[server_msg68_devmod_err.log](https://github.com/fido-alliance/fdo-fido-conformance-server/files/12741030/server_msg68_devmod_err.log)

## What part of the spec are you testing?

- [ ] Rendezvous Server
- [ ] Device Onboarding Service
- [x] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [ ] TO1
- [x] TO2

## Issue description
- During message 68, when client sends all "devmod" modules, conformance owner fails parsing and outputs following error 
   
> Type 255 [100, 68, "Done70: Error encrypting...cbor: cannot unmarshal array into Go struct field 
>     fdoshared.DeviceServiceInfo681.ServiceInfo of type uint8", 1695831800, 1705115730729185836]

- Upon debugging it is observed that conformance owner only accepts two values as declared at https://github.com/fido-alliance/fdo-fido-conformance-server/blob/main/core/shared/sims.go#L55 which is not in accordance with description in spec https://tinyurl.com/devmodtab

- Client and Conformance Logs are attached for reference

**Comment by herrjemand** [comment] 2023-10-01 04:02
Duplicate of #55

**Closed by herrjemand** 2023-10-01 04:02 UTC
